baseURL = "http://localhost/scaffold"
publishDir = "docs"
title = "ic70"
DefaultContentLanguage = "en"
theme = "149"
summaryLength = 55
paginate = 2

[params]
  SearchFormEnabled = false # set false to hidden search function 
  RelatedPostNumber = 6

[taxonomies]
   tag = "tags"
   category = "categories"

[Languages]
  # Each language has its own menu.
  [Languages.en]
    languageCode        = "en"
    LanguageName        = "English"
    description         = "Another site made with Hugo"
    weight              = 1
    contentDir          = "content/en"

  [Languages.it]
    languageCode        = "it"
    LanguageName        = "Italiano"
    description         = "Un'altro sito fatto con Hugo"
    weight              = 2
    contentDir          = "content/it"


